//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sx.Vx.Quipu.WinUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sx.Vx.Quipu.WinUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount should be integer and be between {0} and {1}..
        /// </summary>
        internal static string AmountRangeError {
            get {
                return ResourceManager.GetString("AmountRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} currency is not supported yet..
        /// </summary>
        internal static string CurrencyIsNotSupportedYet {
            get {
                return ResourceManager.GetString("CurrencyIsNotSupportedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default limit is already set..
        /// </summary>
        internal static string DefaultLimitIsAlreadySetError {
            get {
                return ResourceManager.GetString("DefaultLimitIsAlreadySetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default limit must be set..
        /// </summary>
        internal static string DefaultLimitMustBeSetError {
            get {
                return ResourceManager.GetString("DefaultLimitMustBeSetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path must be specified..
        /// </summary>
        internal static string FilePathMustBeSpecified {
            get {
                return ResourceManager.GetString("FilePathMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More ....
        /// </summary>
        internal static string FirstCurrencyComboBoxItemName {
            get {
                return ResourceManager.GetString("FirstCurrencyComboBoxItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap globe_16 {
            get {
                object obj = ResourceManager.GetObject("globe.16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the end of term.
        /// </summary>
        internal static string InterestPaymentAtTheEndOfTerm {
            get {
                return ResourceManager.GetString("InterestPaymentAtTheEndOfTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitalization / day.
        /// </summary>
        internal static string InterestPaymentCapitalizationByDay {
            get {
                return ResourceManager.GetString("InterestPaymentCapitalizationByDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitalization / month.
        /// </summary>
        internal static string InterestPaymentCapitalizationByMonth {
            get {
                return ResourceManager.GetString("InterestPaymentCapitalizationByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitalization / quarter.
        /// </summary>
        internal static string InterestPaymentCapitalizationByQuarter {
            get {
                return ResourceManager.GetString("InterestPaymentCapitalizationByQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitalization / year.
        /// </summary>
        internal static string InterestPaymentCapitalizationByYear {
            get {
                return ResourceManager.GetString("InterestPaymentCapitalizationByYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every months.
        /// </summary>
        internal static string InterestPaymentEveryMonth {
            get {
                return ResourceManager.GetString("InterestPaymentEveryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every quater.
        /// </summary>
        internal static string InterestPaymentEveryQuarter {
            get {
                return ResourceManager.GetString("InterestPaymentEveryQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every year.
        /// </summary>
        internal static string InterestPaymentEveryYear {
            get {
                return ResourceManager.GetString("InterestPaymentEveryYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest rate should be integer and be between {0} and {1}..
        /// </summary>
        internal static string InterestRateRangeError {
            get {
                return ResourceManager.GetString("InterestRateRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max amount must be greater than zero..
        /// </summary>
        internal static string MaxAmountMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("MaxAmountMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max interest rate must be greater than zero..
        /// </summary>
        internal static string MaxInterestRateMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("MaxInterestRateMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max term must be greater than zero..
        /// </summary>
        internal static string MaxTermMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("MaxTermMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min amount must be greater than zero..
        /// </summary>
        internal static string MinAmountMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("MinAmountMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min interest rate must be greater than zero..
        /// </summary>
        internal static string MinInterestRateMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("MinInterestRateMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min term must be greater than zero..
        /// </summary>
        internal static string MinTermMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("MinTermMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of the {0} property must be greater then zero, but it is {1}..
        /// </summary>
        internal static string PropertyMustBeGreaterThenZero {
            get {
                return ResourceManager.GetString("PropertyMustBeGreaterThenZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of the {0} property must be integer, but it is {1}..
        /// </summary>
        internal static string PropertyMustBeInteger {
            get {
                return ResourceManager.GetString("PropertyMustBeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        internal static string TermCaptionSuffix {
            get {
                return ResourceManager.GetString("TermCaptionSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term should be integer and be between {0} and {1}..
        /// </summary>
        internal static string TermRangeError {
            get {
                return ResourceManager.GetString("TermRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string UnhandledErrorCaption {
            get {
                return ResourceManager.GetString("UnhandledErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something goes wrong. Please contact the authors.\r\n\r\n{0}.
        /// </summary>
        internal static string UnhandledErrorMessage {
            get {
                return ResourceManager.GetString("UnhandledErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Calculator.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
